### PR TITLE
added user friendly error messages to errors

### LINKED ISSUE #47: User friendly error codes
Our dependants end up writing maps like these for user friendly error codes:

https://github.com/meshcollider/VaxVerifyNZ/blob/2c4841185baae2de7af3754a36fe77787ae82286/screens/ResultModal.js#L12

this should be provided in the library

### PR DESCRIPTION
**Pull request by J-eld**
Fixes #47 

- Added user friendly error messages, please check for validity.

- [x] Tests pass

### CODE REVIEW

**Comment by noway** [comment]
@wseagar thoughts on this? This will help with people re-implementing their own error messages: https://github.com/meshcollider/VaxVerifyNZ/blob/2c4841185baae2de7af3754a36fe77787ae82286/screens/ResultModal.js#L12

We should also think if we want to expose things like NBF and EXP

**Comment by wseagar** [comment]
Looks good to me. Can we also add these into the documentation?

**Comment by J-eld** [comment]
Just added to the docs. Not sure about the wording tho

**Review by noway — APPROVED** [review]
SHIP IT 🚢

**Pull request merged**
